Update machine-learning-terms.md
haltakov/suboptimal pull request #14
Opened 2021-05-20 22:35 UTC by ansegura7

The definitions of the ML concepts hyperparameters and parameters have been added.

2021-05-29 21:36 UTC, haltakov requested changes
Thank you for contributing these explanations! These are useful concepts that people should recognize and distinguish and which may be confusing. 

I suggested some changes to the formulations. Let me know what you think :)

2021-05-29 21:36 UTC, haltakov commented on explanations/machine-learning-terms.md
> +        <li>Hidden units</li>
"Number of neurons in each layer" is more accurate I think

2021-05-29 21:36 UTC, haltakov commented on explanations/machine-learning-terms.md
> +        <li>Hidden layers</li>
"Number of hidden layers"?

2021-05-29 21:36 UTC, haltakov commented on explanations/machine-learning-terms.md
> +        <li>Number of epochs</li>
I would add "... to train the model"

2021-05-29 21:36 UTC, haltakov commented on explanations/machine-learning-terms.md
> +    <p>They indicate what the model looks like and how it will be trained. For example, in the case of neural networks:</p>
I would suggest reformulating this a bit.

"Hyperparameters specify the model's architecture and how it will be trained."

2021-05-29 21:36 UTC, haltakov commented on explanations/machine-learning-terms.md
> +    <p>They indicate what the model looks like and how it will be trained. For example, in the case of neural networks:</p>
I would also add that these parameters are not learned during training.

2021-05-29 21:36 UTC, haltakov commented on explanations/machine-learning-terms.md
> +    <p>These are the internal variables of the model that will be updated during the training phase, for example, in the case of neural networks, the weights or biases of the network.</p>
I would start a bit differently: "The model parameters are there internal..."

2021-05-31 16:05 UTC, ansegura7 reviewed
The suggested wording changes were made.

2021-05-31 16:05 UTC, ansegura7 commented on explanations/machine-learning-terms.md
> +    <p>They indicate what the model looks like and how it will be trained. For example, in the case of neural networks:</p>
Great, totally agree with this and the following suggestions.
The changes are implemented in the next PR.

2021-06-01 21:05 UTC, haltakov approved these changes

2021-06-01 21:05 UTC, haltakov commented
Cool, let's merge this!

2021-06-01 21:06 UTC, merged