Update machine-learning-terms.md
haltakov/suboptimal pull request #15
Opened 2021-06-03 12:15 UTC by creatornadiran

2021-06-09 21:02 UTC, haltakov requested changes
Thanks for your contribution! I like your description and the examples, but I would like to make some small changes to make it even better. I left some comments with a couple of ideas. I will be glad to hear your opinion on that!

2021-06-09 21:02 UTC, haltakov commented on explanations/machine-learning-terms.md
> +<td valign="top">Loss (Cost) Functions</td>
I would skip the Cost part here and just call it Loss Function. You can mention later in the text that it is sometimes also called a cost function.

2021-06-09 21:02 UTC, haltakov commented on explanations/machine-learning-terms.md
> +    <p>Functions that help to evaluate your model.</p>
I think this needs to be a bit more precise. The loss function is important during training and is usually not very suitable to evaluate the performance of the model.

Maybe something like: "A function that is used to evaluate the performance of a model and guide the training process."

2021-06-09 21:02 UTC, haltakov commented on explanations/machine-learning-terms.md
> +    <p>Loss Functions show the error between what value your model predicts and what the value actually is. Gradient descent is applied to these functions to find the least error. Some common ones ar
Maybe mention that it needs to be differentiable.

2021-06-10 12:58 UTC, creatornadiran commented
Thank you for your ideas. I agree with all your comments and made the necessary changes.

2021-06-10 19:46 UTC, haltakov approved these changes
Cool, thanks for the modifications! Let's merge this.

2021-06-10 19:46 UTC, merged